version: "3"

services:
  db:
    # latest image as of writing
    image: postgres:12.17
    environment:
      POSTGRES_USER: "gpig"
      POSTGRES_DATABASE: gpig
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbfiles:/var/lib/postgresql/data"
  dmas:
    build: ./DMAS
    ports:
      - "8081:8080"
    volumes:
      - ./dmas_config.ini:/app/config.ini
      - ./DMAS/models/human_detection/weights/human_classification_weights.pkl:/app/models/human_detection/weights/human_classification_weights.pkl
    environment:
      CONFIG_FILE: "/config.ini"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  dronemanager:
    build: ./DroneManager
    ports:
      - "8082:8080"

volumes:
  dbfiles:
  kafkafiles:
