version: "3"

services:
  db:
    # latest image as of writing
    image: postgres:12.17
    environment:
      POSTGRES_USER: "gpig"
      POSTGRES_DATABASE: gpig
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbfiles:/var/lib/postgresql/data"
  dmas:
    build: ./DMAS
    ports:
      - "8081:8080"
    volumes:
      - ./dmas_config.ini:/config.ini
    environment:
      CONFIG_FILE: "/config.ini"
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  dronemanager:
    build: ./DroneManager
    ports:
      - "8082:8080"
  llm:
    build: ./LLM
    ports:
      - "8083:8080"
    environment:
      IS_DEMO: 'true'
      MODEL_SOURCE: 'local'
      LLM_MODEL_PATH: '/models/gemma-1.1-2b-it.gguf'
      VITE_DMAS_ENDPOINT: 'http://dmas:8080'
    volumes:
      - ./LLM/models:/models

volumes:
  dbfiles:
  kafkafiles:
