version: "3"

services:
  kafka:
    # latest image as of writing
    image: bitnami/kafka:3.6.1
    volumes:
      - "kafkafiles:/bitnami/kafka"
  db:
    # latest image as of writing
    image: postgres:12.17
    environment:
      POSTGRES_USER: "gpig"
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbfiles:/var/lib/postgresql/data"
  dmas:
    build: ./DMAS
    ports:
      - "8081:8080"
  dronemaanger:
    build: ./DroneManager
    ports:
      - "8082:8080"

volumes:
  dbfiles:
  kafkafiles:
