name: Update Submodules

on:
  schedule:
    - cron: '0 6-22/2 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Submodules
        run: scripts/update-submodules.sh
